### PR TITLE
fix(langgraph): preModelHook `llmInputMessages` should not keep concatenating messages

### LINKED ISSUE #1316: 【BUG】Agent node cannot intercept messages normally after combining trimMessage
trimMessage works fine, but for some reason, there is a problem when passing it to the next agent node.

As shown in the figure, the final result returned by trimMessage is "Tell me another one", which is correct.

Image

But the message sent to llm in the end sent all human messages.

Image

Image

Here is my code
```
  private readonly trimMessages = trimMessages({
    maxTokens: 50,
    tokenCounter: new ChatOpenAI({ model: 'gpt-4o' }),
    strategy: 'last',
    includeSystem: true,
    startOn: 'human',
  });

```
```
  createReactAgent({
        llm: this.getModel(model),
        tools,
        prompt,
        name,
        checkpointer,
        responseFormat,
        preModelHook: async (state) => {
          const messages = await this.trimMessages.invoke(state.messages);
          return { llmInputMessages: messages };
        },
      });
```

### PR DESCRIPTION
**Pull request by dqbd**
Closes #1316

### CODE REVIEW

File: libs/langgraph/src/prebuilt/react_agent_executor.ts [hunk 1]
```diff
@@ -457,7 +457,7 @@ type WithStateGraphNodes<K extends string, Graph> = Graph extends StateGraph<
 
 const PreHookAnnotation = Annotation.Root({
   llmInputMessages: Annotation<BaseMessage[], Messages>({
-    reducer: messagesStateReducer,
+    reducer: (_, update) => messagesStateReducer([], update),
```
Comment (Diluka) [inline libs/langgraph/src/prebuilt/react_agent_executor.ts:460]: Why don‘t you return it directly, but use that function again? Does it have any special function?

Comment (dqbd) [reply libs/langgraph/src/prebuilt/react_agent_executor.ts:460]: We want to make sure that (1) we're sending the same messages state-wise (assigning IDs if they are not present) and (2) we still accept `Messages` as update instead of just `BaseMessage[]`
