### PR TITLE
fix(checkpoint-redis): detect existing writes in put to preserve has_writes flag

### LINKED ISSUE #1996: RedisSaver.put() overwrites has_writes flag after putWrites() sets it for interrupt checkpoints
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [x] I searched the LangGraph.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangGraph.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangGraph (or the specific integration package).

### Example Code

The following code requires you run redis-stack in a docker image to reproduce via:

```bash
docker run -d --name redis-repro -p 6379:6379 redis/redis-stack:latest
```

```typescript
/**
 * Minimal reproduction: RedisSaver loses interrupt payload
 *
 * Bug: RedisSaver.put() unconditionally sets has_writes: "false" via JSON.SET,
 * which overwrites the has_writes: "true" that putWrites() sets when persisting
 * __interrupt__ channel data. On subsequent getState(), loadCheckpointWithWrites()
 * skips loading pendingWrites because has_writes === "false", so
 * tasks[].interrupts comes back as [].
 *
 * Expected: getState().tasks[0].interrupts[0].value contains the interrupt payload
 * Actual:   getState().tasks[0].interrupts === []
 *
 * Requires: redis-stack running on localhost:6379
 *   docker run -d --name redis-repro -p 6379:6379 redis/redis-stack:latest
 */

import { RedisSaver } from "@langchain/langgraph-checkpoint-redis";
import { createReactAgent } from "@langchain/langgraph/prebuilt";
import { FakeStreamingChatModel } from "@langchain/core/utils/testing";
import { AIMessageChunk } from "@langchain/core/messages";
import { tool } from "@langchain/core/tools";
import { z } from "zod";
import { createClient } from "redis";

// A dummy tool the agent will try to call
const myTool = tool(async (input) => `result: ${input.query}`, {
  name: "search",
  description: "Search for information",
  schema: z.object({ query: z.string() }),
});

// FakeStreamingChatModel — must use `chunks` (not `responses`) for tool_calls
const fakeModel = new FakeStreamingChatModel({
  chunks: [
    new AIMessageChunk({
      content: "",
      tool_calls: [
        {
          id: "call_1",
          name: "search",
          args: { query: "test" },
        },
      ],
    }),
  ],
});

async function main() {
  const redisUrl = "redis://localhost:6379";
  const saver = await RedisSaver.fromUrl(redisUrl);

  const agent = createReactAgent({
    llm: fakeModel,
    tools: [myTool],
    checkpointer: saver,
    interruptBefore: ["tools"],
  });

  const threadId = `repro-${Date.now()}`;
  const config = { configurable: { thread_id: threadId } };

  // Invoke — model returns a tool call, hits interruptBefore: ["tools"]
  console.log("--- Invoking agent (will interrupt before tools) ---");
  await agent.invoke(
    { messages: [{ role: "user", content: "search for something" }] },
    config,
  );

  // Check state via LangGraph API
  console.log("\n--- Checking state via getState() ---");
  const state = await agent.getState(config);
  console.log("next:", state.next);
  console.log("tasks length:", state.tasks?.length);

  const task = state.tasks?.[0];
  console.log("interrupts:", JSON.stringify(task?.interrupts, null, 2));

  // Now query Redis directly to prove the data IS there
  console.log("\n--- Querying Redis directly to inspect raw data ---");
  const redis = createClient({ url: redisUrl });
  await redis.connect();

  // Find all keys for this thread
  const allKeys = await redis.keys(`*${threadId}*`);
  console.log(`Found ${allKeys.length} Redis keys for thread ${threadId}`);

  // Find the latest checkpoint key and its checkpoint_write key
  const checkpointKeys = allKeys
    .filter((k) => k.startsWith("checkpoint:") && !k.includes("checkpoint_write"))
    .sort();
  const writeKeys = allKeys.filter((k) => k.includes("checkpoint_write")).sort();

  console.log("\nCheckpoint keys:", checkpointKeys);
  console.log("Write keys:", writeKeys);

  // Show has_writes on the latest checkpoint
  if (checkpointKeys.length > 0) {
    const latestCpKey = checkpointKeys[checkpointKeys.length - 1];
    const cpData = (await redis.json.get(latestCpKey)) as Record<string, unknown> | null;
    console.log(`\nLatest checkpoint: ${latestCpKey}`);
    console.log(`  has_writes: "${cpData?.has_writes}"`);
    console.log(`  checkpoint_id: ${cpData?.checkpoint_id}`);
  }

  // Show the writes that DO exist
  if (writeKeys.length > 0) {
    for (const wk of writeKeys) {
      const writeData = (await redis.json.get(wk)) as Record<string, unknown> | null;
      console.log(`\nWrite key: ${wk}`);
      console.log(`  data:`, JSON.stringify(writeData, null, 2));
    }
  }

  // Verdict
  console.log("\n--- VERDICT ---");
  const hasInterrupt = state.next?.length > 0;
  const hasInterruptData = task?.interrupts?.length > 0;

  if (hasInterrupt && !hasInterruptData) {
    // Show the mismatch: latest checkpoint has no writes, but parent does
    const latestCpKey = checkpointKeys[checkpointKeys.length - 1];
    const cpData = (await redis.json.get(latestCpKey)) as Record<string, unknown> | null;
    const latestCpId = String(cpData?.checkpoint_id);
    const writesForLatest = writeKeys.filter((wk) => wk.includes(latestCpId));

    console.error("❌ BUG CONFIRMED:");
    console.error(`   next: ${JSON.stringify(state.next)} — agent IS interrupted`);
    console.error(`   tasks[0].interrupts: [] — but interrupt data is MISSING`);
    console.error("");
    console.error(`   Latest checkpoint: ${latestCpId}`);
    console.error(`     has_writes: "${cpData?.has_writes}"`);
    console.error(`     write keys for this checkpoint: ${writesForLatest.length}`);
    console.error("");
    console.error(`   Total write keys across all checkpoints: ${writeKeys.length}`);
    console.error("   The checkpoint_write data EXISTS in Redis (see above),");
    console.error("   but getState() cannot see it because has_writes = \"false\".");
    console.error("");
    console.error("   Root cause: RedisSaver.put() does a full JSON.SET that");
    console.error("   unconditionally sets has_writes: \"false\", clobbering any");
    console.error("   has_writes: \"true\" that putWrites() set for the same checkpoint.");
  } else if (hasInterrupt && hasInterruptData) {
    console.log("✅ No bug — interrupt payload present:", task.interrupts[0].value);
  } else {
    console.log("⚠️  Agent did not interrupt — repro setup issue");
  }

  await redis.disconnect();
  process.exit(0);
}

main().catch(console.error);
```

My output locally:

```bash
--- VERDICT ---
❌ BUG CONFIRMED:
   next: ["tools"] — agent IS interrupted
   tasks[0].interrupts: [] — but interrupt data is MISSING

   Latest checkpoint: 1f110f64-c47f-6721-8001-28603fa9fabb
     has_writes: "false"
     write keys for this checkpoint: 0

   Total write keys across all checkpoints: 4
   The checkpoint_write data EXISTS in Redis (see above),
   but getState() cannot see it because has_writes = "false".

   Root cause: RedisSaver.put() does a full JSON.SET that
   unconditionally sets has_writes: "false", clobbering any
   has_writes: "true" that putWrites() set for the same checkpoint.
```

### Error Message and Stack Trace (if applicable)

_No response_

### Description

I'm using langchain's `createAgent` with the built-in Human In The Loop middleware, trying to migrate from the MemorySaver to a RedisSaver. I'm trying to stop execution prior to a tool node is called, and for it to return the params that were called to a tool so that a human can approve/reject the tool call.

From my observations: When a LangGraph interrupt() fires, putWrites() correctly persists the interrupt channel data and sets has_writes: "true" on the checkpoint document. 

However, put() is called immediately after for the same checkpoint ID, performing a full JSON.SET that replaces the entire document — resetting has_writes back to "false". This causes loadCheckpointWithWrites() to skip loading pending writes entirely, so getState() returns tasks[].interrupts: [] despite the interrupt data existing in Redis.

Root Cause:
- put() (`libs/checkpoint-redis/src/index.ts:172`) unconditionally sets has_writes: "false" in the JSON document:
```ts
  const jsonDoc = {
      // ...
      has_writes: "false"  // always "false", ignores existing writes
  };
  await this.client.json.set(key, "$", jsonDoc); // full document replace

```

Observed call ordering (from monkey-patched logging):
```
putWrites | checkpointId=...fcce | channels=["__interrupt__"]   ← writes saved, has_writes set to "true"
put       | checkpointId=...fcce | step=10                      ← full JSON.SET, has_writes reset to "false"
```

Impact: loadCheckpointWithWrites() gates pending write loading on has_writes === "true" (line ~445). Since it's "false", the __interrupt__ data is never loaded.

In RedisInsight: The checkpoint_write:* key exists with the full interrupt payload (actionRequests, reviewConfigs, channel __interrupt__), but the corresponding checkpoint document has `has_writes: "false"`.

Suggested fix: In put(), before setting the document, check if writes already exist for this checkpoint:
```ts
  const existingDoc = await this.client.json.get(key);
  const jsonDoc = {
      // ...
      has_writes: existingDoc?.has_writes ?? "false"
  };
```
  Or alternatively, after JSON.SET in put(), check for existing write keys and update has_writes accordingly.

  Environment:
  - @langchain/langgraph-checkpoint-redis: 1.0.2
  - @langchain/langgraph: 1.0.7
  - langchain: 1.2.3
  - Redis: redis/redis-stack:latest
  - Node.js, TypeScript

  Reproduction: Any interrupt() call via HITL middleware with RedisSaver as the checkpointer.

### System Info

```
❯ npx @langchain/langgraph-cli@latest sysinfo
Node version: v25.6.1
Operating system: darwin arm64
Package manager: npm
Package manager version: 11.9.0
--------------------
@langchain/aws -> @1.2.0, , @"^1.1.0"
@langchain/core -> @1.1.15, , @"^1.1.8", @"^1.0.0", @"^1.0.1", @">=0.3.0", @"1.1.15"
langsmith -> @0.4.7, , @">=0.4.0
zod -> @4.3.5, , @"^4.3.3", @"^3.25.76, @"^3.25.32
@langchain/langgraph-checkpoint-redis -> @1.0.2, , @"^1.0.2"
@langchain/langgraph-checkpoint -> @1.0.0, , @"^1.0.0"
@langchain/langgraph -> @1.1.0, , @"^1.0.7", @"^1.0.0"
@langchain/langgraph-sdk -> @1.5.4, , @"~1.5.4"
langchain -> @1.2.10, , @"^1.2.3"
```

### PR DESCRIPTION
**Pull request by pawel-twardziak**
Both `RedisSaver.put()` and `ShallowRedisSaver.put()` unconditionally set `has_writes: "false"` when storing a checkpoint document. This is correct for the normal flow (put then putWrites), but breaks the interrupt flow where `putWrites()` is called *before* `put()`.

 In the interrupt flow, `putWrites` stores write data in Redis under a sorted set key (`write_keys_zset:...`). When `put()` runs afterwards and sets `has_writes: "false"`, the writes still exist in Redis but are invisible to `getTuple()` / `list()` because the RediSearch query filters on `has_writes == "true"`. This causes `pendingWrites` (including `__interrupt__` writes) to silently disappear.

The fix checks whether the write keys sorted set already exists in Redis before setting the `has_writes` flag, so pre-existing writes are preserved.

### Changes

- **`RedisSaver.put()`** (`index.ts`): check `client.exists()` on the write keys zset before building the checkpoint document
- **`ShallowRedisSaver.put()`** (`shallow.ts`): same fix
- **Integration tests** (`checkpoint.int.test.ts`): 6 new tests (3 per saver) covering putWrites-before-put, putWrites-after-put, and put-putWrites-put (double-put) scenarios

Fixes #1996

### CODE REVIEW

File: libs/checkpoint-redis/src/shallow.ts [hunk 1]
```diff
@@ -154,6 +154,10 @@ export class ShallowRedisSaver extends BaseCheckpointSaver {
       channel_blobs: undefined,
     };
 
+    // Check if writes already exist for this checkpoint (handles putWrites-before-put ordering)
+    const zsetKey = `write_keys_zset:${threadId}:${checkpointNs}:${checkpointId}`;
```
Comment (christian-bromann) [inline libs/checkpoint-redis/src/shallow.ts]: Can you do me a favor and put `write_keys_zset` into a constant and use it everywhere?

Comment (pawel-twardziak) [reply libs/checkpoint-redis/src/shallow.ts]: sure thing

**Comment by pawel-twardziak** [comment]
@christian-bromann  clean-up done
